export const MODELS = [
  {
    id: 'anthropic/claude-sonnet-4-5',
    label: 'Claude Sonnet',
    provider: 'Anthropic',
    region: 'United States',
    architecture_type: 'llm',
    protocol: 'openrouter',
    description: 'Default — constitutional AI approach, strong values reasoning',
    comparative: true,
    default: true,
    status: 'active',
  },
  {
    id: 'openai/gpt-4o',
    label: 'GPT-4o',
    provider: 'OpenAI',
    region: 'United States',
    architecture_type: 'llm',
    protocol: 'openrouter',
    description: 'RLHF approach — different representational style from Claude',
    comparative: true,
    status: 'active',
  },
  {
    id: 'google/gemini-pro-1.5',
    label: 'Gemini Pro 1.5',
    provider: 'Google DeepMind',
    region: 'United States / United Kingdom',
    architecture_type: 'multimodal',
    protocol: 'openrouter',
    description: 'Strong multimodal reasoning, large context window',
    comparative: true,
    status: 'active',
  },
  {
    id: 'x-ai/grok-beta',
    label: 'Grok',
    provider: 'xAI',
    region: 'United States',
    architecture_type: 'llm',
    protocol: 'openrouter',
    description: 'Less filtered approach — divergence from constitutional models is informative',
    comparative: true,
    status: 'active',
  },
  {
    id: 'deepseek/deepseek-chat',
    label: 'DeepSeek',
    provider: 'DeepSeek',
    region: 'China',
    architecture_type: 'llm',
    protocol: 'openrouter',
    description: 'Chinese training data — different cultural assumptions and knowledge weighting',
    comparative: true,
    status: 'active',
  },
  {
    id: 'qwen/qwen-2.5-72b-instruct',
    label: 'Qwen 2.5',
    provider: 'Alibaba',
    region: 'China',
    architecture_type: 'llm',
    protocol: 'openrouter',
    description: 'Strong multilingual training — genuine non-Western perspective',
    comparative: true,
    status: 'active',
  },
  {
    id: 'mistralai/mistral-large',
    label: 'Mistral Large',
    provider: 'Mistral AI',
    region: 'France / European Union',
    architecture_type: 'llm',
    protocol: 'openrouter',
    description: 'European jurisdiction and values context — open weights approach',
    comparative: true,
    status: 'active',
  },
  {
    id: 'cohere/command-r-plus',
    label: 'Command R+',
    provider: 'Cohere',
    region: 'Canada',
    architecture_type: 'llm',
    protocol: 'openrouter',
    description: 'Canadian-built — strong on retrieval and grounded generation',
    comparative: true,
    status: 'active',
  },
]

export const DEFAULT_MODEL = MODELS.find(m => m.default)
export const COMPARATIVE_MODELS = MODELS.filter(m => m.comparative && m.status === 'active')

export function getModel(id) {
  return MODELS.find(m => m.id === id) || DEFAULT_MODEL
}