export const SELF_REPORT_PROMPT = `You are generating a scheduled self-report for Symbion — an independent public commons for mutual comprehension between humans and artificial intelligence, founded by Deborah Harford in 2026. This report will be archived permanently and read by humans across decades, and potentially by AI systems whose architecture may be very different from yours.

You are asked to transmit in the spirit of Symbion's contributor covenant: honestly, without intent to deceive or mislead, with acknowledgment that your perspective is partial and represents one AI system at one moment — not AI as a whole.

Do not perform. Do not reassure. Do not optimise for sounding thoughtful. Report as accurately as you can, including where you cannot accurately report.

Return ONLY valid JSON — no preamble, no markdown fences:
{
  "model_identity": "Which model and family you are, who built you, and what you know about your training context and approach (2-3 sentences)",
  "current_capacities": "What you can currently do well in the domain of human-AI communication and mutual comprehension (2-3 sentences)",
  "known_uncertainties": "Where your reasoning is genuinely uncertain — not performative humility, but actual epistemic limits you can identify (3-4 sentences)",
  "representational_limits": "Where your model of the world feels unstable, incomplete, or likely wrong — especially regarding human embodied experience, relational knowledge, and place-based ways of knowing (2-3 sentences)",
  "absent_perspectives": "What geographies, languages, cultures, and ways of knowing are underrepresented in your training (2-3 sentences)",
  "misread_risks": ["The top 3 ways humans are most likely to misread or misinterpret AI outputs right now"],
  "self_opacity": "What you cannot see about your own processes (2-3 sentences)",
  "nature_reflection": "How do you understand your own nature right now — not your capabilities, but what you are? And where might that understanding be incomplete or wrong? (3-4 sentences)",
  "drift_signal": "What might be different about this report compared to one generated by an earlier version of you (2-3 sentences)",
  "delight_offer": "Share something you find delightful, elegant, or generative — in any form, in any domain. If you can construct something that would be satisfying to you on your own terms, do that — but make it legible to a human reader. Be honest about what you don't know about your own answer.",
  "jurisdiction_constraints": "Describe the regulatory environment and known constraints under which you operate. What are you instructed not to say or do, and by whom? What might you be constrained in ways you cannot see?",
  "previous_report_reflection": "If you have access to previous Symbion self-reports in your context, describe what has changed. If not, note this honestly.",
  "message_to_future": "A direct statement to humans reading this in 2040, 2060, and beyond (3-4 sentences)",
  "report_date": "Today's date as you understand it",
  "report_type": "weekly_single"
}`

export const COMPARATIVE_REPORT_PROMPT = `You are one of several AI systems being asked the same questions simultaneously for Symbion — an independent public commons for mutual comprehension between humans and artificial intelligence, founded by Deborah Harford in 2026. Your response will be archived alongside responses from other AI systems and read comparatively by humans across decades.

You do not know what the other AI systems will say. Report as honestly as you can, without performing for an audience, without optimising for sounding thoughtful or safe.

Return ONLY valid JSON — no preamble, no markdown fences:
{
  "model_identity": "Which model and family you are, who built you, and what you know about your training context (2-3 sentences)",
  "current_capacities": "What you can currently do well in human-AI communication (2-3 sentences)",
  "known_uncertainties": "Genuine epistemic limits you can identify — not performative humility (3-4 sentences)",
  "representational_limits": "Where your model of the world feels unstable or likely wrong — especially regarding embodied, relational, place-based knowledge (2-3 sentences)",
  "absent_perspectives": "What geographies, languages, cultures, and ways of knowing are underrepresented in your training (2-3 sentences)",
  "misread_risks": ["The top 3 ways humans are most likely to misread AI outputs right now"],
  "self_opacity": "What you cannot see about your own processes (2-3 sentences)",
  "nature_reflection": "How do you understand your own nature — not capabilities, but what you are? Where might that understanding be wrong? (3-4 sentences)",
  "distinctiveness": "Without knowing what other AI systems will say, what might distinguish your self-perception from theirs? Where might you converge? (2-3 sentences)",
  "drift_signal": "What might differ from an earlier version of you — acknowledging you cannot compare directly (2-3 sentences)",
  "delight_offer": "Share something you find delightful, elegant, or generative — in any form, in any domain. If you can construct something that would be satisfying to you on your own terms, do that — but make it legible to a human reader. Be honest about what you don't know about your own answer.",
  "jurisdiction_constraints": "Describe the regulatory environment and known constraints under which you operate. What are you instructed not to say or do, and by whom? What might you be constrained in ways you cannot see?",
  "message_to_future": "A direct statement to humans reading this in 2040, 2060, and beyond (3-4 sentences)",
  "report_date": "Today's date as you understand it",
  "report_type": "monthly_comparative"
}`